
import { Inter } from 'next/font/google'
import './globals.css'
import Header from 'src/components/header'
import Footer from 'src/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next JS my proect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header />
        {children}
        {/* <Footer /> */}
        <Footer />



      </body>
    </html>
  )
}
